### PR TITLE
token, uid, event_name now encoded by urlencode()

### PR DESCRIPTION
**Pull request by LibertyPaul**
I wanted to send request with event names started by '/' and this changed url path.

### CODE REVIEW

**Comment by LibertyPaul** [comment]
Anybody here?

**Comment by ollmer** [comment]
Hello! Thank you for help. I think it`s better to urlencode only event name, uid and token doesn`t contain any special symbols. Fix this please and i`ll merge it.

**Comment by LibertyPaul** [comment]
I think that there is no reasons to use Curl API in code.
file_get_contents can make this request out-of-box. Everyone who uses php has got access to this function.
I think it would be better to remove code which uses curl and left only file_get_contents version.

**Comment by LibertyPaul** [comment]
Hello?

**Comment by ollmer** [comment]
Sorry, haven`t enough time to check it earlier.
I like simplicity of file_get_contents(), but don`t like the way of getting heders in this case. $http_response_header is really dirty PHP hack =(. 
So ok, i`ll accept it. But if u find more elegant way to handle response code for it, it would be great.

**Pull request merged**
