### PR TITLE
Relicense under dual MIT/Apache-2.0

### PR DESCRIPTION
**Pull request by knsd**
Closes: #47

### CODE REVIEW

**Comment by ziahot935** [comment]
I used it

**Comment by hkrahi** [comment]
I receive it

**Comment by knsd** [comment]
@ollmer, @pshishkin 

It's been two months already. Are you going to accept the pull request or not?

**Comment by ferfarz** [comment]
How

**Comment by ollmer** [comment]
Sure it will, but after code split, which is not finished yet/

**Comment by knsd** [comment]
Okay, I understand that you want to split all languages into separate repositories. But the thing that I can not understand — why can't you just merge it now, instead of waiting for months before you have time to do your split thing. Merging this PR won't harm your split in any ways, so I urge you to do it now.

**Pull request closed without merging**
